title: "Sean M. Gonzalez"
description: "Technical Product Manager • Full-Stack Engineer • Web3 Builder"
theme: jekyll-theme-cayman

# Optional: show downloads button if you add files later
show_downloads: false
